on: [push]

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: Send test message

    steps:
    - id: initial
      uses: juztcode/gitter-github-action@v1
      with:
        room-id: ${{ secrets.GITTER_ROOM_ID }}
        token: ${{ secrets.GITTER_TOKEN }}
        text: Pending

    - uses: juztcode/gitter-github-action@v1
      with:
        room-id: ${{ secrets.GITTER_ROOM_ID }}
        token: ${{ secrets.GITTER_TOKEN }}
        text: Success
        message-id: ${{ steps.initial.outputs.message-id }}
